version: "3.9"

services:
  kurs:
    build: .
    container_name: pln_kurs
    image: avmiki80/kurs
    restart: always
    ports:
      - '8081:8081'
    networks:
      - network-kurs
  kursui:
    build: .
    container_name: pln_kursui
    image: avmiki80/kursui
    restart: always
    ports:
      - '8080:8080'
    networks:
      - network-kurs

networks:
  network-kurs: